<#assign EEE_title = "XQuery Queries with embedded AQL for EHR "+requestAttributes.ehr_id><#include "header.html.ftl">
<h1>${EEE_title}</h1>
<p>This page contains query examples that generate:
<ul>
	<li><a href="#table">HTML Table</a></li>
	<li><a href="#smart">SMART RDF</a> as defined by <a href="http://smartplatforms.org/">http://smartplatforms.org/</a></li>
	<li><a href="#"></a></li>
</ul>
</p>

<p>Parameters that have names prefixed with "x_ser_option_" can be used to control <b>Xquery serialization</b> options, see
<ul>
	<li>Main reference: <a href="http://www.w3.org/TR/xslt-xquery-serialization-30/">http://www.w3.org/TR/xslt-xquery-serialization-30/</a></li>
	<li>or the older:   <a href="http://www.w3.org/TR/2010/REC-xslt-xquery-serialization-20101214/">http://www.w3.org/TR/2010/REC-xslt-xquery-serialization-20101214/</a></li>
	<li>Namespace info: <a href="http://www.w3.org/2010/xslt-xquery-serialization/">http://www.w3.org/2010/xslt-xquery-serialization/</a></li>
<!-- <li> (BaseX specifics: <a href="http://docs.basex.org/wiki/Serialization">http://docs.basex.org/wiki/Serialization</a>)</li> -->
</ul>
</pre>
</p>
<hr/>
<h2 id="table">HTML-table generating query</h2>
<p><FORM 
	METHOD=POST 
	ENCTYPE="application/x-www-form-urlencoded" 
	ACTION="./">
  Query: <br/>
<textarea name="query" ROWS="10" COLS="100">
<h:html xmlns:h="http://www.w3.org/1999/xhtml" xmlns:eee="http://www.imt.liu.se/mi/ehr/2010/EEE-v1.xsd" xmlns="http://schemas.openehr.org/v1">
<h:head>
	<h:title>Composition list</h:title>
	<h:link rel="stylesheet" href="/static/css/style1.css" type="text/css"/> 
	<h:link rel="stylesheet" href="/css/timeline3.css" type="text/css"/>
</h:head>
<h:body>
<h:table>
  <h:tr><h:th>Date</h:th><h:th>Label</h:th><h:th>Facility</h:th><h:th>Clinician</h:th><h:th>Setting</h:th></h:tr>
{let $aqlResult := 
<eeeq:aql>
   SELECT 
	 v/uid/value as composition_id,
	 c/name/value as composition_title,
	 c/context/start_time/value as comp_start_time,
	 c/composer/name as comp_composer, 
	 c/context/health_care_facility/name as comp_facility,		
	 c/context/setting as comp_setting		
	FROM Ehr e[ehr_id/value=$current_ehr_uid] 
	CONTAINS VERSION v 
	CONTAINS COMPOSITION c 
	ORDER BY c/context/start_time/value
</eeeq:aql> 		

  for $res in $aqlResult/res:results/res:result
  return <h:tr>
    <h:td>{$res//*[@name = 'comp_start_time']/value/text()}</h:td>
    <h:td><h:a href="/ehr:{$current_ehr_uid}/{$res//*[@name = 'composition_id']/value/text() }">{$res//*[@name = 'composition_title']/value/text() }</h:a></h:td>
    <h:td>{$res//*[@name = 'comp_facility']/name/text()}</h:td>
    <h:td>{$res//*[@name = 'comp_composer']/name/text()}</h:td>
    <h:td><h:span class="openEHR-setting-{$res//*[@name = 'comp_setting']/setting/defining_code/code_string/text()}">{$res//*[@name = 'comp_setting']/setting/value/text()}</h:span></h:td>
  </h:tr>
}
</h:table>
</h:body></h:html>	
</textarea> <br/>
<input type="checkbox" name="debug" value="true" /> Use debug mode (query translation only) <INPUT TYPE=SUBMIT VALUE="Submit">
<p>XML serialisation options:<br/>
omit-xml-declaration: <select name="x_ser_option_omit-xml-declaration">
<option value="yes">yes</option>
<option value="no" selected="selected">no</option></select>

Media: <select name="x_ser_option_method">
<option value="text">text</option>
<option value="xml" selected="selected">xml</option></select>
</p>
</FORM>
</p>
<p>The variable <em>$current_ehr_uid</em> is available to the query execution; when submitting the query to this URI it has the value <em>${requestAttributes.ehr_id}</em></p>
<hr/>



<h2 id="smart">SMART generating query (unfinished)</h2>
<p><FORM 
	METHOD=POST 
	ENCTYPE="application/x-www-form-urlencoded" 
	ACTION="./">
  Query: <br/>
<textarea name="query" ROWS="20" COLS="100">
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:sp="http://smartplatforms.org/terms#"
  xmlns:dcterms="http://purl.org/dc/terms/"
  xmlns:v="http://www.w3.org/2006/vcard/ns#"
  xmlns:spcode="http://smartplatforms.org/terms/codes/">
{let $aqlResult := 
 <eeeq:aql>
   SELECT 
	 v/uid/value as composition_id,
	 c/name/value as composition_title,
	 c/context/start_time/value as comp_start_time,
	 c/context/end_time/value as comp_end_time, 
	 c/context/health_care_facility/name as comp_facility,		
	 c/context/setting/defining_code/code_string as comp_setting		
	FROM Ehr e[ehr_id/value=$current_ehr_uid] 
	CONTAINS VERSION v 
	CONTAINS COMPOSITION c 
	ORDER BY c/context/start_time/value
 </eeeq:aql> 		

(: TODO 1: Figure out if SMART allows pointing back to specific openEHR COMPOSITION URI instead of entire record :)
(: In that case it could be generated by "/ehr:{$current_ehr_uid}/{$res//*[@name = 'composition_id']/value/text() }" :)
(: TODO 2: Add if/switch converting openehr settings (comp_setting) to SMART encounter type :)

  for $res in $aqlResult/res:results/res:result
  return
   
      <sp:Encounter>
      <sp:belongsTo rdf:resource="/records/{$current_ehr_uid}/{$res//*[@name = 'composition_id']/value/text()}" />
      <sp:startDate>{$res//*[@name = 'comp_start_time']/value/text()}</sp:startDate>
      <sp:endDate>{$res//*[@name = 'comp_end_time']/value/text()}</sp:endDate>
      <sp:encounterType>
       <sp:CodedValue>
         <dcterms:title>{$res//*[@name = 'composition_title']/value/text()}</dcterms:title>
         <sp:code>
          <spcode:EncounterType rdf:about="http://smartplatforms.org/terms/codes/EncounterType#ambulatory">
            <rdf:type rdf:resource="http://smartplatforms.org/terms#Code" /> 
            <dcterms:title>Ambulatory encounter</dcterms:title>
            <sp:system>http://smartplatforms.org/terms/codes/EncounterType#</sp:system>
            <dcterms:identifier>ambulatory</dcterms:identifier> 
          </spcode:EncounterType>       
         </sp:code>
       </sp:CodedValue>
      </sp:encounterType>
    </sp:Encounter>
}    
</rdf:RDF>

	
</textarea> <br/>
<input type="checkbox" name="debug" value="true" /> Use debug mode (query translation only) <INPUT TYPE=SUBMIT VALUE="Submit">
<p>XML serialisation options:<br/>
omit-xml-declaration: <select name="x_ser_option_omit-xml-declaration">
<option value="yes">yes</option>
<option selected="selected" value="no">no</option></select>

</p>
</FORM>
<h2>Related Resources</h1>
<p>One step up in the Resource hierarchy: <a href="../">../</a></p>
<#include "footer.html.ftl">